from keyboards.buttons import key_board_main
from keyboards.buttons import key_board_search
from keyboards.buttons import key_board_spam
from keyboards.buttons import key_board_choise
from keyboards.buttons import inline_key_board_dragstore
from keyboards.buttons import key_board_dragstore